### ISSUE TITLE
Finalize plugin interface naming, families, and directory structure

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#169]
# Requested Update

### Description
* Finalize plugin interface naming and directory structure for main geoips repo once and for all.

### Background and Motivation
* We have never fully finalized the names.

#### Locations used

ie, if <interface_name> = algorithms (use the plural)
then <singular_yaml_interface_name> = algorithm (use the singular)

**Actual interface Python modules (actual interface class names internal to the python modules must also be updated):**
Found in 
`geoips/geoips/interfaces/yaml_based/<interface_name>.py`
`geoips/geoips/interfaces/module_based/<interface_name>.py`

**Directories of actual plugins of each interface**:
`geoips/geoips/plugins/yaml/<interface_name>/`
`geoips/geoips/plugins/modules/<interface_name>/`

**Schema for product_defaults base YAML plugins**:
`geoips/geoips/schema/product_defaults/bases/<singular_yaml_interface_name>.yaml`
* algorithm
* colormap
* coverage_checker
* interpolator
* windbarbs (WE WILL DEAL WITH THIS LATER)

**Schema for YAML-based interfaces**
Must update within the file as well.
`geoips/geoips/schema/<interface_name>/<family>.yaml`

**List of <interface_name> interfaces that need updated**

* algorithms
* sector_loaders, family "dynamic_area_definition" <- area_def_generators
* feature_annotators <- boundaries
* colormaps
* coverage_checkers <- coverage_checks
* sectors, family "static_area_definition" <- static_sectors
* sectors, family "dynamic_area_definition" <- dynamic_sectors
* filename_formatters <- filename_formats
* gridline_annotators <- gridlines
* interpolators <- interpolation
* output_formatters <- output_formats
* procflows
* product_defaults <- product_params
* products, family "list" <- product_inputs
* readers
* title_formatters <- title_formats
* sector_loaders, family "trackfile" <- trackfile_parsers

This might be separate, and not stored internal to repo necessarily:
* procflow_configs (quasi-interface, driving full processing of EVERYTHING)

### Alternative Solutions
* Keep questioning what names we settled on.
  
### Environment
* geoips >= 1.9.1

### Code to demonstrate issue
* Once everything is refactored, ensure $GEOIPS/tests/test_full_install.sh returns successfully.

### Checklist for Completion

**Reorganization**
* [x] `geoips/geoips/interfaces/yaml_based/<interface_name>.py`  Jeremy
* [x] `geoips/geoips/interfaces/module_based/<interface_name>.py` Jeremy
* [x] `geoips/geoips/plugins/yaml/<interface_name>/` Mindy
  * [x] geoips/geoips/plugins/yaml/sector_loaders/dynamic_area_definitions (was area_def_generators)
  * [x] geoips/geoips/plugins/yaml/sector_loaders/trackfiles (was trackfile_parsers)
* [x] `geoips/geoips/plugins/modules/<interface_name>/` Mindy
* [x] `geoips/geoips/schema/product_defaults/bases/<singular_yaml_interface_name>.yaml` Jeremy
* [x] `geoips/geoips/schema/product_defaults/bases/<singular_yaml_interface_name>.yaml` Jeremy

**Update files in the reorg to reflect new families/interface names**
* [x] geoips/interfaces/module_based/<interface_name>.py
  * [x] Update each class name to match interface name
* [x] geoips/interfaces/yaml_based/<interface_name>.py
  * [ ] The contents of these will be updated when yaml_based interfaces are implemented
* [x] geoips/schema/<interface_name>/<family_name>
* [ ] geoips/schema/bases/<singular_interface_name>.yaml
* [ ] geoips/schema/bases/base.yaml
* [ ] geoips/plugins/yaml/<interface_name>/<plugin_name>.yaml
  * [ ] geoips/plugins/yaml/sectors/dynamic/
  * [ ] geoips/plugins/yaml/sectors/static/

**Update files to match updated schema**
* [ ] geoips/plugins/yaml/product_defaults
  * [ ] Update all YAMLsto match schema
* [ ] geoips/plugins/yaml/products/<source>.yaml
  * [ ] Update each product in list to match products/by_source.yaml schema (barbs and colormaps)
  * [ ] Contents of defaults overrides needs to match 
 
**Make it work**
* [ ] Update all __init__.py files
* [ ] Write classes for YAML interfaces.
* [ ] Update all the code to use the new YAML interface classes.

### Interfaces
* [x] algorithms
* [x] sector_loaders <- area_def_generators
* [x] feature_annotators <- boundaries
* [x] colormaps
* [x] coverage_checkers <- coverage_checks
* [x] sectors, family "area_definition" <- static_sectors
* [x] sectors, family "dynamic_area_definition" <- dynamic_sectors
* [x] filename_formatters <- filename_formats
* [x] gridline_annotators <- gridlines
* [x] interpolators <- interpolation
* [x] output_formatters <- output_formats
* [x] procflows
* [x] product_defaults <- product_params
* [x] products, family "by_source" <- product_inputs
* [x] readers
* [x] title_formatters <- title_formats
* [ ] trackfile_parsers

**Comment by jsolbrig** [comment]
Complete.
