### ISSUE TITLE
Add interfaces for current "ghost" interfaces

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#200]
# Requested Update

### Description
There are a number of ghost interfaces in GeoIPS right now that need to be made into real interfaces. These include:
- sector_spec_generator
- sector_metadata_generator
- coverage_checkers
- sector_adjusters
- output_comparisons

**Comment by jsolbrig** [comment]
@mindyls I believe that this is complete but am unsure about `output_comparisons`. If `output_comparisons` is the only one that is not complete, can you close this and create a new issue?

**Comment by mindyls** [comment]
All of these are complete except output_comparisons.  I'll create a new issue for that interface.
