### ISSUE TITLE
Move required functions from `geoips/dev/utils.py` to `geoips/geoips_utils.py` then delete `geoips/dev/utils.py`

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#207]
# Requested Update

### Description
We should move all required functions from `geoips/dev/utils.py` to `geoips/geoips_utils.py`. Then we should delete `geoips/dev/utils.py`.

### Background and Motivation
Currently there are a number of functions that are used from `geoips/dev/utils.py` but we will be getting rid of the `geoips/dev/` directory. We should move anything that we want to keep to `geoips/geoips_utils.py` and delete anything that we don't need.

Current functions in `geoips/dev/utils.py`:
- `deprecation`: Currently unused, but maybe useful in the future. Maybe keep it, but move it to `geoips_utils.py`?
- `replace_geoips_paths`: Currently used in the files listed below. Should move to `geoips_utils.py` for now, but assess whether it is actually required once we are able to install GeoIPS without `-e`.
  - metadata_default.py
  - metadata_tc.py
  - bdeck_parser.py
  - tc_tracks.py
- `copy_standard_metadata`: Currently used in the files listed below. Should move to `geoips_utils.py` and update all imports.
  - Update imports in interp_nearest, interp_grid, interp_gauss,
      netcdf_geoips, and single_source
- `get_required_geoips_xarray_attrs`: This appears to be unused, but maybe it's needed for some plugins? Recommend removal.
- `output_process_times`: Currently used in the files listed below. Should move to `geoips_utils.py` and update all imports.
  - Update imports in data_fusion.py, config_based.py, single_source.py, and the
      ahi_hsd reader

### Checklist for Completion
* [ ]

**Comment by jsolbrig** [comment]
@mindyls Can you give your thoughts on this?

**Comment by mindyls** [comment]
I think we will need replace geoips paths

**Comment by jsolbrig** [comment]
So far, I decided to move these all to `geoips_utils.py`. I think that there is only one place in data_fusion that will be impacted and nothing in either geoips_clavrx or recenter_tc. I don't know if it will impact anything else.

Basically, though, it just means replacing anything like `from geoips.dev.utils import ...` with `from geoips.geoips_utils import ...`.
