### ISSUE TITLE
Add support for product_params_override with new ProductInterface

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#222]
# Requested Update

### Description
* product_params_override can be specified in procflow_configs or command line - must add support to new ProductInterface in order to pull information out of "product_params_override" and insert it into the product.

### Background and Motivation
*  [ OPTIONAL: Provide additional detailed information and background related to this issue ]

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by jsolbrig** [comment]
Complete
