### ISSUE TITLE
Add ProcflowConfig Interface and schema

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#223]
# Requested Update

### Description
* procflow_configs are still specified via the old interface / formatting.  Update procflow config to new interface.

### Background and Motivation
*  [ OPTIONAL: Provide additional detailed information and background related to this issue ]

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by jsolbrig** [comment]
@mindyls I don't remember what this is. Can you take a look at it?

**Comment by jsolbrig** [comment]
This will fall out of the order-based procflow work.
