### ISSUE TITLE
Improve unit test suite for validating contents of plugins

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#224]
# Requested Update

### Description
* Add unit tests that actually ensure contents of plugins are valid (ie, each plugin referenced within a YAML plugin exists, arguments are valid, etc).

### Background and Motivation
*  Currently test_yaml_plugins only tests that they are valid schema - add an additional test to fully validate the contents of the plugins.
* Possibly additionally have more exhaustive module-based tests that ensure return values are correct?

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by jsolbrig** [comment]
I believe that this issue is outdated and, if any of it still does need to be handled, we will see that in our current projects. Closing.
