### ISSUE TITLE
Duplicate plugins with the same ID should raise a PluginError

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#230]
# Requested Update

### Description
Plugin IDs should be required to be unique within its interface across all packages. When a non-unique plugin ID is encountered a PluginError should be raised.

The error should state:
- interface name
- plugin ID
- the names of all packages where that plugin ID was encountered
  - I expect that this will error as soon as it encounters a conflict, so probably just one or two packages

Note that I'm saying "ID" rather than "name". This is because some interfaces may have plugins whose names conflict but whose IDs are more complex. An example of this is the Products interface whose plugin IDs are tuples containing `name` and `source_name`.

### Checklist for Completion
* [ ]

**Comment by evrose54** [comment]
I'm working on a PR right now that should fix this. Done as a top level unit test when package plugin registries are created.
