### ISSUE TITLE
Finalize required_args, required_kwargs, known_kwargs

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#231]
# Requested Update

NOTE: I think we need to implement the second option below - create a separate YAML with the required_args and required_kwargs for each family.  I believe we decided against including "known_kwargs" or "allowable_kwargs".

### Description
Module-based plugin families are defined by their their arguments and keywords. Currently the list of required arguments and keywords are defined in dictionaries in each interface. The dictionaries are class-level attributes named `required_args`, `required_kwargs`, and `allowable_kwargs` whose keys are family names and whose values are lists of argument names.

We should finalize how this functionality works and figure out where it should be implemented.
- Finalize naming for these dictionaries. Suggested: `required_args`, `required_kwargs`, and `known_kwargs`
- Determine how these should be implemented. Options include:
  1. Continue using class-level dictionaries in each interface (kind of hides things)
  2. Define in YAML files for each family describing their required and allowable parameters (would be more explicit and easier to create a new family) **this is probably the best option**
  3. Create classes for each new family (would require actual code edits)

### Checklist for Completion
* [ ]

**Comment by jsolbrig** [comment]
@mindyls Can you take a look at this to be sure it is complete? I'm fairly sure that we can close this.

**Comment by mindyls** [comment]
I don't think we did implement this - they are still specified as a single dictionary directly within the interface module with all families specified in one place. 

I think we need to implement the logic to specify the required_args and required_kwargs in a separate YAML file for each family.  This will allow us to specify families from outside the main geoips repo (right now all families have to be listed directly within the interface module in the geoips repo).

**Comment by jsolbrig** [comment]
I am not sure that we would get much tangible benefit from this and we will likely be making changes to how some of this works as part of the order-based procflow. I'm going to close this and we can revisit if we see a need in the future.

@mindyls FYI
