### ISSUE TITLE
Product Plugin Script Improvement

### ISSUE THREAD

**Issue by SRIKANTH-KUMAR** [NRLMMD-GEOIPS/geoips#232]
# Requested Update

### Background and Motivation
*  When the user runs the script from tests/scripts/script.sh to process and generate the image. 

### Description
*  The image name almost appears hidden in log file directed to the standard out. It would be difficult especially for first time users to figure out the image name with an ease. 
* Additionally, ask the user if they wish to view the image and display if user responds with a "y|Y"

### Alternative Solutions
*  Place the generated image name post success message at the end
* Alternatively provide clear white space before and after the image name if it's not feasible to print at the end. 
![image](https://github.com/NRLMMD-GEOIPS/geoips/assets/30406205/ddc2dc9c-6b4b-481c-a3eb-23dedbe08045)

**Comment by jsolbrig** [comment]
This is partially handled by #285 which addresses the excess logging.

Remaining issues here:
- We should be able to add extra white-space around the image outputs to make them more obvious. Another alternative might be adding some color to the terminal output.
- We can look into automatic image display, but it might be difficult to achieve when we support several different platforms.

**Comment by jsolbrig** [comment]
I think we can call this complete at this point.
