### ISSUE TITLE
Change Sector Schema to allow multiple items of information in the metadata

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#248]
# Requested Update

### Description
*  This issue has been created to allow greater flexibility with sector metadata. By changing the metadata structure to allow multiple types of information (region, padding info, sector_family...), we won't just be limited to defining the location of the sector. This allows for flexibility to add more types of information in the future as well.

### Checklist for Completion
* [ ]  Change area_definition.yaml 
* [ ]  Update current sector yamls to adhere to new structure

**Comment by jsolbrig** [comment]
Closed as completed by #248.
