### ISSUE TITLE
Create GEOring_3D reader for GeoIPS

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#253]
# Requested Update

### Description
This issue has been created as a feature request for a GEOring_3D reader. This would help with the development of OVERCAST, and is a feature that would be very beneficial for users with access to this data. Creating a reader would allow users to plot data anywhere in the world.

### Checklist for Completion
* Create a reader for GEOring_3D data.

**Comment by jsolbrig** [comment]
Closing this. Handled by https://github.com/NRLMMD-GEOIPS/overcast_package
