### ISSUE TITLE
BUG: Make geotiffs right side up

### ISSUE THREAD

**Issue by cpcamacho** [NRLMMD-GEOIPS/geoips#30]
# Requested Update

### Description
*  Currently geotiffs are upside down. Flip them over.​

### Background and Motivation
*  We do not want upside down GeoTIFFs. It will confuse people.
* imagery_annotated opposite geotiff output viewed in Google Earth​

### Alternative Solutions
*  Put a warning that the user must view geotiffs upside down...​
* Rotate monitors
  
### Environment
* geoips repo, v1.4.8+​

### Code to demonstrate issue
![image](https://github.com/NRLMMD-GEOIPS/geoips/assets/13873624/63a69d1b-519d-484f-9b9f-a49632d52dbd)

*  $GEOIPS/tests/scripts/ahi.WV.geotiff.sh will produce above upside down geotiff.​

 @mindyls ADD PICTURE!

### Checklist for Completion
* [  ] GeoTIFFS are right side up.

**Comment by jsolbrig** [comment]
FYI, @evrose54 when you get to this issue, @lance-wilson has worked on this some and might have some thoughts on what has/hasn't worked here.
