### ISSUE TITLE
Bug Fix: Update geostationary readers to support multiple scan times

### ISSUE THREAD

**Issue by cpcamacho** [NRLMMD-GEOIPS/geoips#312]
# Requested Update

### Description
*  The geostationary readers currently only support reading in one scan time. They should be capable of reading in multiple scan times.

### Background and Motivation
*  Follow geostationary readers need to be updated to support multiple scan times:
  * abi_netcdf
  * ahi_hsd
  * seviri_hrit
* Easiest path forward will be to simply place a wrapper around the main ingest function in these readers, and loop through files grouped by scan time

### Alternative Solutions
*  Leverage future satpy reader
  
### Environment
*  geoips >= 1.11.3a0

### Code to demonstrate issue
*  Run following test scripts to make sure we do not break existing functionality
  * `$GEOIPS_PACKAGES_DIR/geoips/tests/scripts/abi.static.Infrared.imagery_annotated.sh`
  * `$GEOIPS_PACKAGES_DIR/geoips/tests/scripts/ahi.tc.WV.geotiff.sh`
  * `$GEOIPS_PACKAGES_DIR/geoips/tests/scripts/seviri.WV-Upper.unprojected_image.sh`

### Checklist for Completion
* [x] Update abi_netcdf reader
* [x] Update ahi_hsd reader
* [x] Update seviri_hrit reader

**Comment by mindyls** [comment]
@cpcamacho  We can help  @SRIKANTH-KUMAR  @Srikant-Kumar-Gampa  with this.   He will start looking through your linked branch here, get familiar with what it is doing, and ask as he has questions.

@evrose54 will share his GLM reader that currently loops through multiple scan times (this is handled differently, but may help inform development)

**Comment by mindyls** [comment]
This is Kumar.  Again, should add him so we can tag.

**Comment by SRIKANTH-KUMAR** [comment]
Clears the tests listed and ready for review through [this](https://github.com/NRLMMD-GEOIPS/geoips/pull/427) pull-request
