### ISSUE TITLE
Add log with emphasis function

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#377]
# Requested Update

### Description
Add either LOG.emphasis, or a shared log_with_emphasis function, or LOG.interactive(..., with_emphasis=True)  that will include ***** or other emphasis.
Per:
* https://github.com/NRLMMD-GEOIPS/recenter_tc/pull/28/files#r1361099566
* 

### Background and Motivation
*  [ OPTIONAL: Provide additional detailed information and background related to this issue ]

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by jsolbrig** [comment]
On this one, I prefer `log.interactive(..., add_emphasis=True)` over the other two solutions. I don't know if that is possible, though.

**Comment by jsolbrig** [comment]
Also note that this will need to be applied to the other plugin repos.

**Comment by mindyls** [comment]
Current 1.12.0 update has an example of putting the emphasis around the whole log block, rather than around each line.  Update PR accordingly, and this is good to go.
