### ISSUE TITLE
Add GitHub Actions for style enforcement

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#38]
# Requested Update

### Description
*  Add GitHub Actions to enforce following the GeoIPS style guide

### Background and Motivation
*  Currently the geoips style guide is not enforced. Add GitHub Actions to implement enforcement for the style guides referenced in documentation_strategy.rst
    * https://github.com/NRLMMD-GEOIPS/geoips/blob/main/docs/documentation_strategy.rst
    * NOTE: Google docstrings will likely be updated to NumPY docstrings #29 

### Alternative Solutions
*  Wild West.
  
### Environment
*  All NRLMMD-GEOIPS repos >= 1.5.1

### Code to demonstrate issue
*  PRs will fail if style guide is not followed properly

### Checklist for Completion
* [  ] docstring formatting: https://www.pydocstyle.org/en/stable/error_codes.html#default-conventions
* [  ] flake8
* [  ] pylint
* [  ] bandit

**Comment by jsolbrig** [comment]
@mindyls this doesn't appear to be running right now because we weren't ready to start enforcing. I think we have the actions already written and they just need to be enabled. Are we ready to turn this on?

**Comment by jsolbrig** [comment]
This is complete. Actions currently run automatically for all PRs and pushes to those PRs.

**Comment by mindyls** [comment]
Added link to 1.11.2 release notes
