### ISSUE TITLE
Rethink How to Implement BaseYamlnterface 'get_plugins()'

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#383]
# Requested Update

### Description
With the addition of the create_plugin_registry PR (see #240), we have greatly improved the import speed for GeoIPS. However, in doing so, we placed some unnecessary stress on other functions, such as BaseYamlInterface, get_plugins, and correspondingly, 'get_plugin'. I'm not sure if there is an easy fix for this, but get_plugins is very slow for the Products interface.

### Background and Motivation
Our whole purpose of the #240 PR was to improve the efficiency of GeoIPS as a whole. We should not add inefficiencies to other parts of the code to achieve efficiencies elsewhere.

### Alternative Solutions
Leave it as is, or find a middle ground between our old implementation and our new one.
  
### Related Comments
See [this comment](https://github.com/NRLMMD-GEOIPS/geoips/pull/240/files#r1370419238), which demonstrates the code where this issue stems from.

**Comment by mindyls** [comment]
This may still be somewhat applicable, but get_plugins is very infrequently called so low priority for now.  May be an issue for CLI if it takes too long.  This would only be used with cli

**Comment by jsolbrig** [comment]
Will not do for now. Reopen if needed.
