### ISSUE TITLE
Add documentation for how plugin registries are created

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#386]
# Requested Update

### Description
With the addition of plugin registries (see #240), there is a need to add documentation to explain how these registries are created. It's a complex process involving discovering all available plugins in every package, and users should be informed of this process so they know the structure of how packages should be organized for the future.

It might be smart to add a new section GeoIPS documentation for just this process. 

### Background and Motivation
This is a large update for GeoIPS and should be documented appropriately. These plugin registries define how GeoIPS will locate the appropriate plugins, and is involved in many of the inner-workings of GeoIPS. It's important to have this process documented for both users and developers.

**Comment by mindyls** [comment]
This just needs to be reviewed.  Probably merge after 1.12 is released and merged.

**Comment by mindyls** [comment]
@SRIKANTH-KUMAR will review PR
