### ISSUE TITLE
Write plugin registries into 'home/.config/geoips/'

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#388]
# Requested Update

### Description
Create plugin registries (see #240) currently writes the registries into the package-level subdirectory of each package. While this works, we should consider writing these registries into `$HOME/.config/geoips/`, so it's more hidden behind the scenes and is used more as a configuration file for GeoIPS rather than a visible yaml file which users might delete on accident.

### Background and Motivation
Many applications use this directory as a location to store configuration files pertinent to their software. It seems reasonable that these registries could be written there for a similar purpose for GeoIPS. This doesn't have to work, but may be a good idea to play around with this to see if we can get it working.

Currently this is being written to the installed package directory inside `site-packages/`. This is likely to cause problems when GeoIPS or plugin packages are installed from wheels/eggs. 

### Alternative Solutions
Leave the code as is. It works!

**Comment by mindyls** [comment]
Potential issue if someone has more than one version of geoips installed
