### ISSUE TITLE
Investigate moving tuple-based product plugin name creation to plugin registry class

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#393]
# Requested Update

### Description
*  Possibly move the _create_plugin_registry_name method from the Interface classes onto the PluginRegistry class.  This may not be necessary, but keep it in mind as an option as the PluginRegistry is developed.

### Background and Motivation

Currently, when we have a plugin of type “list” it has special logic to handle loading plugins from within the list and constructing appropriate names for those subplugins. Since the interface classes will no longer be directly accessing plugins and, instead, using the registry for just about everything, we should be able to move the logic that handles subplugins out of base.py and into create_plugin_registries. Then, when we build the registries, we would do the translation that we need to do there, rather than in the interface classes.

* When creating the plugin registry, we must assemble the (product_name, source_name) as the final product "name" within the ProductInterface (all other interfaces just use a single plugin name, not a tuple, so do not have to override the "create_registered_plugin_name" method): https://github.com/NRLMMD-GEOIPS/geoips/blob/395a69e6377314e332ef2960c714f191baefab3e/geoips/create_plugin_registries.py#L324
* Product plugins define their own registered plugin names, based on product name and source name: https://github.com/NRLMMD-GEOIPS/geoips/blob/395a69e6377314e332ef2960c714f191baefab3e/geoips/interfaces/yaml_based/products.py#L98

Since we are creating the tuple (product_name, source_name) plugin name up front during the plugin registry creation, perhaps we no longer need the logic for assembing plugin_name = (product_name, source_name) within the Product Interface (since at that point, we already know the plugin name, because it is fully defined within the plugin registry, and we access the products through the registry.  If we move the logic for assembing the (product_name, source_name) plugin name onto the plugin registry, then we do not need to import from the interfaces, and we may avoid some circular imports. 

### Alternative Solutions
* Leave the create_registered_plugin_names logic within the interface code. 
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by mindyls** [comment]
@evrose54 is going to investigate to ensure this has been addressed.  We think by the time the plugin registry was complete, this was no longer an issue.  But I'm not 100% sure.

**Comment by evrose54** [comment]
This hasn't been addressed yet. Personally, I would just leave the code as is, however I'm happy to have a conversation about this to get everyones opinions'.

**Comment by mindyls** [comment]
@evrose54 says this is good, and it isworking when creating the plugin registries and at runtime.  Closing as completed.
