### ISSUE TITLE
Review initial "Extending GeoIPS with Plugins" documentation

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#399]
# Requested Update

### Description
* Reminder for Jeremy to fully review "Extending GeoIPS with Plugins" documentation was not fully reviewed by Jeremy.  Reminder for him to look through it in conjunction with the PR to expand the "Extending GeoIPS with Plugins" documentation.

### Background and Motivation
* https://github.com/NRLMMD-GEOIPS/geoips/pull/330
* https://github.com/NRLMMD-GEOIPS/geoips/issues/398

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by evrose54** [comment]
This was merged in the v1_12_2 release. See #330. Closing this issue now.
