### ISSUE TITLE
Consider how tests should be run

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#4]
# Requested Update

### Description
Currently GeoIPS testing is handled via shell scripts that are not a part of the actual Python package. This is problematic because we can't call the tests from an installed version of GeoIPS, only from the source directory.

We should migrate to a test system that uses Python as a method of calling the tests and expose a `geoips test` (or similar) option via setup.py.

### Background and Motivation
Currently the test scripts are in `geoips/tests/scripts` but are not callable from an installed version of GeoIPS.

**Comment by biosafetylvl5** [comment]
Related: #513
