### ISSUE TITLE
Discuss how we should install GeoIPS Repositories and Test Datasets for the long-run

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#447]
# Requested Update

### Description
We should discuss how we want to install available GeoIPS repositories alongside their test datasets for the foreseeable future. Currently, they are installed via a bash script (geoips/setup/check_system_requirements.sh), which will download data via http get requests and install repositories via a git clone / pip install -e command in the correct directory.

### Background and Motivation
While a bash script works, we should consider refactoring this code to into the GeoIPS CLI (see #444, which stems from #37). For example, it would be nice to be able to run ``geoips config install <test_dataset_name>``, which would install the dataset to the correct location, and decompress it. Namely, having the CLI be able to perform this would easily allow the user to install test data when needed, rather than having it installed the entire time, which can waste space.

It would also be nice to have the CLI be able to clone and install other GeoIPS Repositories, without having to go through the manual process of cloning the correct URL and installing it.

### Alternative Solutions
Leave the code as is. For more information on the install process, see ``geoips/tests/integration_tests/full_install.sh`` and ``geoips/setup/check_system_requirements.sh``.

### Checklist for Completion
* [x] Generate a list of what packages and test data are installed.
* [x] How are items in the list installed? Get requests, git clone, pip install, ...
* [x] Where are these items downloaded from?
* [ ] Develop a method for installing these items for the foreseeable future
* [ ] Implement this method within the GeoIPS CLI.

**Comment by evrose54** [comment]
Test data is currently installed via a http GET request to the dataset URL, which is then decompressed using tar. The code below demonstrates this ``python $SCRIPT_DIR/download_test_data.py $test_data_url | tar -xz -C $GEOIPS_TESTDATA_DIR >> $install_log 2>&1``, where $SCRIPT_DIR = geoips/setup.

GeoIPS packages are retrieved using a git clone request to the correct URL, and installed via a pip install -e . in the location of the retrieved repository.

**Comment by evrose54** [comment]
List of test data URLs installed:
```
test_data_urls=(
    "https://io.cira.colostate.edu/s/mQ2HbE2Js4E9rba/download/test_data_viirs.tgz"
    "https://io.cira.colostate.edu/s/CezXWwXg4qR2b94/download/test_data_smap.tgz"
    "https://io.cira.colostate.edu/s/HyHLZ9F8bnfcTcd/download/test_data_scat.tgz"
    "https://io.cira.colostate.edu/s/snxx8S5sQL3AL7f/download/test_data_sar.tgz"
    "https://io.cira.colostate.edu/s/fkiPS3jyrQGqgPN/download/test_data_noaa_aws.tgz"
    "https://io.cira.colostate.edu/s/LT92NiFSA8ZSNDP/download/test_data_gpm.tgz"
    "https://io.cira.colostate.edu/s/DSz2nZsiPMDeLEP/download/test_data_fusion.tgz"
    "https://io.cira.colostate.edu/s/ACLKdS2Cpgd2qkc/download/test_data_clavrx.tgz"
    "https://io.cira.colostate.edu/s/FmWwX2ft7KDQ8N9/download/test_data_amsr2.tgz"
)
```

**Comment by evrose54** [comment]
List of GeoIPS packages cloned and installed:
```
geoips
data_fusion
recenter_tc
geoips_clavrx
geoips_plugin_example
template_basic_plugin
template_fusion_plugin
```
Where their base url is ``https://github.com/NRLMMD-GeoIPS``

**Comment by jsolbrig** [comment]
This look good, @evrose54. Thanks for writing it up.

Just a note, we will be able to install other plugin packages with `pip install <package_name>` in the future. I don't think we need to add the ability to install them to the CLI. I could see an argument for making the CLI able to clone the other packages for development, but I'm not sure if we should do that or not. Maybe it could go under something like `geoips devel-setup` or something like that but I think I'd just leave that part out for now.

**Comment by jsolbrig** [comment]
Closed as not planned.
