### ISSUE TITLE
Provide a more informative error message when --compare_path is used without installing testing dependencies

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#451]
# Requested Update

### Description
Stemming from [this comment](https://github.com/NRLMMD-GEOIPS/geoips/pull/450/files#r1525371612) from this [PR](https://github.com/NRLMMD-GEOIPS/geoips/pull/450), we've came to agreement that we need a better error message when ``--compare_path``, and any other GeoIPS testing functionality is used without the proper testing dependencies installed. 

### Background and Motivation
Currently, when using a fresh installation of geoips (new conda environment,`` pip install $GEOIPS_PACKAGES_DIR/geoips``), and then running ``geoips/tests/integration_tests/base_test.sh``, one of the tests will fail with the following error:

```
Traceback (most recent call last):
  File "/Users/erose/anaconda3/envs/geoips/bin/run_procflow", line 8, in <module>
    sys.exit(main())
  File "/Users/erose/geoips/geoips_packages/geoips/geoips/commandline/run_procflow.py", line 69, in main
    RETVAL = PROCFLOW(COMMAND_LINE_ARGS["filenames"], COMMAND_LINE_ARGS)
  File "/Users/erose/geoips/geoips_packages/geoips/geoips/plugins/modules/procflows/single_source.py", line 1923, in call
    retval += output_checker(
  File "/Users/erose/geoips/geoips_packages/geoips/geoips/plugins/modules/output_checkers/image.py", line 230, in call
    retval = plugin.compare_outputs(
  File "/Users/erose/geoips/geoips_packages/geoips/geoips/interfaces/module_based/output_checkers.py", line 875, in compare_outputs
    ) = self.perform_comparisons(
  File "/Users/erose/geoips/geoips_packages/geoips/geoips/interfaces/module_based/output_checkers.py", line 800, in perform_comparisons
    goodcomps, badcomps, compare_strings = test_product_func(
  File "/Users/erose/geoips/geoips_packages/geoips/geoips/interfaces/module_based/output_checkers.py", line 991, in test_products
    if self.module.outputs_match(
  File "/Users/erose/geoips/geoips_packages/geoips/geoips/plugins/modules/output_checkers/image.py", line 121, in outputs_match
    from pixelmatch.contrib.PIL import pixelmatch
ModuleNotFoundError: No module named 'pixelmatch'
```
As  a developer it may be clear what's going on here, but we need a better error message for general users who are wanting to use GeoIPS testing functionality with their local GeoIPS instance.

### Code to demonstrate issue
Run ``geoips/tests/integration_tests/base_test.sh`` with a new GeoIPS instance with only the base dependencies of the GeoIPS package installed.

### Checklist for Completion
* [ ] Provide a better error for missing ``pixelmatch`` library (stems from ``--compare_path`` being using in run_procflow.
* [ ] Check for other testing functionality used in run_procflow and raise appropriate errors for those as well.

**Comment by biosafetylvl5** [comment]
This error is kind of mute, because you cannot run geoips without `pytest` at the moment because `create_plugin_registries` requires `pytest` which most people will install with the `test` extra. Nonetheless, I fixed the error.

**Comment by biosafetylvl5** [comment]
I also looked for other uses of pixelmatch in geoips - looks like it's just this file:

```bash
gwynu@Gwyns-MacBook-Pro geoips % grep -r pixelmatch .
./geoips/plugins/modules/output_checkers/image.py:        Threshold for the image comparison. Argument to pixelmatch.
./geoips/plugins/modules/output_checkers/image.py:        from pixelmatch.contrib.PIL import pixelmatch
./geoips/plugins/modules/output_checkers/image.py:            "Comparing images using GeoIPS requires a python library called pixelmatch"
./geoips/plugins/modules/output_checkers/image.py:            + " (link: https://pypi.org/project/pixelmatch/)."
./geoips/plugins/modules/output_checkers/image.py:    thresholded_retval = pixelmatch(
./geoips/plugins/modules/output_checkers/image.py:        Threshold for the image comparison. Argument to pixelmatch.
./pyproject.toml:pixelmatch = { version = "*", optional = true }
./pyproject.toml:    "pixelmatch",
./pyproject.toml:    "pixelmatch"
```
