### ISSUE TITLE
Ensure all new Issues and Pull Requests automatically have the GeoIPS All Repos All Functionality board added to Projects

### ISSUE THREAD

**Issue by mindyls** [NRLMMD-GEOIPS/geoips#461]
# Requested Update

### Description
* To ensure all Issues and PRs are reflected in the overall project board, set up a method for automatically adding consistently

### Background and Motivation
*  [ OPTIONAL: Provide additional detailed information and background related to this issue ]

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by biosafetylvl5** [comment]
I added a new workflow that should do this. If it's working for the next week I'll close this issue.
