### ISSUE TITLE
LaTeX not listed as a dependency for building docs in installation instructions

### ISSUE THREAD

**Issue by biosafetylvl5** [NRLMMD-GEOIPS/geoips#466]
# Latex not listed as a dependency for building docs in installation instructions

### Background
- LaTeX is used to build pdf docs
- When building docs without LaTeX the process fails
- LaTeX is not listed as a dependency for building docs in any installation instructions

### Alternative Solutions
* Do nothing and leave users to install after encountering the error
* Warn and pass instead of failing critically 
  
### Environment
*  Tested using the Dockerfile from #452, run `./docs/build_docs.sh` after `pip install -e "$GEOIPS_PACKAGES_DIR/geoips[doc]"`

Output: 

```
ERROR: latex must be installed in order to create pdf documentation.
  try 'module load latex'
```

**Comment by mindyls** [comment]
Note if you call build_docs.sh with the "html_only" argument, it will not attempt to build the pdf.  As in the call in "test_all.sh":

https://github.com/NRLMMD-GEOIPS/geoips/blob/4d260ed31460a6646b3c325bf969799baad66a0e/tests/test_all.sh#L34

For creating documentation, I think html_only is sufficient/preferably, so you don't need to install latex.  It should definitely be documented what the requirements are - but I would tend towards building with "html_only" for general purpose use (unless we're actually deploying the documentation).

**Comment by biosafetylvl5** [comment]
Perhaps I can add this to the docs, but also update the error message to direct users to either install latex/build html only. What do you think?

**Comment by mindyls** [comment]
Yes that sounds good, thanks!

**Comment by biosafetylvl5** [comment]
Awesome! Thanks for helping to bring me up to speed on the build process
