### ISSUE TITLE
Update commandline.ancillary_info.py to regenerate yaml instructions if missing and json is valid (CLI)

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#539]
# Requested Update

### Description
*  [ In 2-3 sentences briefly describe the required bug fix or feature with this issue. ]

### Background and Motivation
*  [ OPTIONAL: Provide additional detailed information and background related to this issue ]

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by jsolbrig** [comment]
I don't see a reason that this should ever happen. I think that, until we actually encounter a real problem, we can ignore this. Closing.
