### ISSUE TITLE
Replace references to GEOIPS_BASEDIR/test_data with GEOIPS_TESTDATA_DIR in test scripts

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#57]
# Requested Update

### Description
We used to use `GEOIPS_BASEDIR/test_data` to locate GeoIPS test data. That has been changed to `GEOIPS_TESTDATA_DIR`. This needs to be updated in a variety of test scripts.

**Comment by mindyls** [comment]
https://github.com/NRLMMD-GEOIPS/geoips/pull/63

This was resolved with the 1.6.1 merge to main.
