### ISSUE TITLE
Give consideration to how many levels are supported in CLI commands

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#574]
# Requested Update

### Description
For example, when retrieving a plugin via ``geoips get / describe``, lets say ``geoips get plugin <interface_name> <plugin_name>``, we could probably remove a level and make this ``geoips get <interface_name> <plugin_name>``. This would result in commands being less verbose and easier to use in general.

Make sure to consider this ideology for all geoips commands.

### Background and Motivation
This stems from a conversation held about #444.

**Comment by jsolbrig** [comment]
I'm going to close this in favor of #756 which describes the same issue in greater detail.
