### ISSUE TITLE
``geoips get package`` should include additional metadata

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#579]
# Requested Update

### Description
``geoips get package`` includes a lot of good information, but we could improve on this. We should update this command to include additional package metadata like: version_number, author, source_link, etc. This way, we expose more information about the package and users get a better sense of what they're using, and where it came from.

### Background and Motivation
This stems from a conversation held about #444.

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
``GeoipsGetPackage`` in ``geoips_get.py``.

**Comment by jsolbrig** [comment]
This can probably be done at the same time as #571. The information should be available via [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html).

**Comment by evrose54** [comment]
To get the version of a package, all you need to do is:
```python
from import.metadata import version

version("geoips") # currently is '1.12.2.post126.dev0'
version("recenter_tc") # currently is '1.12.2a0'
...
```

**Comment by jsolbrig** [comment]
This appears to be complete with #465
