### ISSUE TITLE
Discuss what CLI flags (and their names) should be added to the top level.

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#580]
# Requested Update

### Description
Currently with the CLI, if you call ``geoips``, you'll get minimal info about how to use this command. This exposes subcommands, but that's about it. We should consider making ``geoips`` executable itself, and give it some top level flags such as ``geoips --version`` and ``geoips -l/--loglevel``. Logging would be applied to all subcommands, and ``geoips --version`` is an easy way to see which version of GeoIPS is installed and being used by the user.

We should:
- Discuss the names of these flag
- Generate a list of top level flags that we want to support

### Background and Motivation
This stems from a conversation held about #444.

**Comment by jsolbrig** [comment]
Closed as done.
