### ISSUE TITLE
Discuss whether or not we should implement ``CLI Plugins``

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#631]
# Requested Update

### Description
Per Jeremy's [comment](https://github.com/NRLMMD-GEOIPS/geoips/pull/465#discussion_r1628001227) on #465.
```
What I'd like to do in the long-run, though, is add the ability to have CLI plugins.

We should discuss whether CLI plugins are needed. Maybe they'd be useless after creating the order-based procflow, though.
```
I'm not sure how we'd exactly implement ``CLI Plugins``, but I could see their use cases. It might simplify the CLI a bit more and could be used internally throughout other locations of the code. We'd need to implement an ``internal`` version of the CLI that'd output dictionaries, lists, etc. rather than ``sys.stout`` based output, but that wouldn't be too hard of a refactor.

This is largely just a discussion issue to determine whether or not this factor would be worth it, and what benefits would stem from this change. 

### Background and Motivation
This comes from this [comment](https://github.com/NRLMMD-GEOIPS/geoips/pull/465#discussion_r1628001227) on #465.

### Alternative Solutions
Leave the code as-is.

### Code to demonstrate issue
``geoips.commandline.geoips_run:GeoipsRunDataFusion``

### Checklist for Completion
* [ ] Discuss whether or not ``CLI Plugins`` are worth it in the long run
    * [ ] If they are, discuss how we'd like to implement them
    * [ ] Refactor the CLI to support this type of structure
    * [ ] Implement them
    * [ ] Discuss where else in the code we'd like to use these plugins
    * [ ] Refactor the code to use those plugins.

**Comment by jsolbrig** [comment]
I don't think that I see a use case for this anymore. Closing.
