### ISSUE TITLE
Modify the CLI to output command-specific information for class-factory generated commands

### ISSUE THREAD

**Issue by evrose54** [NRLMMD-GEOIPS/geoips#645]
# Requested Update

### Description
With the addition of #642 and #644 we've added class factories to reduce the amount of levels required to call certain commands, specifically ``geoips list interface <interface_name>``, ``geoips get interface <interface_name>``, ``geoips get plugin <interface_name> <plugin_name>``, and ``geoips get family <interface_name> <family_name>``. We got this to work, however now these commands all default to the same help information, which lists what will be outputted depending on the case in which the command was called.

We should address this issue and try to dynamically grab the correct help message dependent on the command that was called.

Ie. ``geoips get algorithms -h`` would provide help information about retrieving the algorithms interface, whereas ``geoips get algorithm single_channel`` would provide help information about how to retrieve a plugin from the algorithms interface. There is a minute difference but it is large enough that we should explore this issue and fix it sooner rather than later.

### Background and Motivation
This issue stems from this [comment](https://github.com/NRLMMD-GEOIPS/geoips/pull/644#discussion_r1644882242) on PR #644.

### Code to demonstrate issue
* ``geoips.commandline.ancillary_info.cmd_instructions.yaml``
* ``geoips.commandline.geoips_command:CommandClassFactory``
* ``geoips.commandline.geoips_list:GeoipsList``
* ``geoips.commandline.geoips_get:GeoipsGet``

### Checklist for Completion
* Address Class Factory Generated Classes and figure out how to dynamically attach the correct help messages for each of those classes

**Comment by jsolbrig** [comment]
Closing in favor of #709
