### ISSUE TITLE
CoverageError should be moved to top-level errors.py

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#67]
# Requested Update

### Description
Currently CoverageError is defined in `geoips.interface_modules.readers.utils.geostationary_geolocation`. This should be moved to the top-level errors.py module.

### Background and Motivation
This is just in a weird location and we should consolidate error classes in errors.py anyway.

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ] Find all uses of CoverageError
* [ ] Ensure that it isn't redefined anywhere
* [ ] Move to errors.py
* [ ] Update imports where used
* [ ] Run tests using config-based product

**Comment by mindyls** [comment]
This sounds good @jsolbrig

**Comment by jsolbrig** [comment]
@mindyls Would it be worth looking through GeoIPS for other custom error classes, then consolidate them all to the top-level `errors.py` file? Maybe that's what this issue should actually be?
