### ISSUE TITLE
Migrate `interface_modules` to `plugins`

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#70]
# Requested Update

### Description
Currently, plugins internal to GeoIPS are housed in the `interface_modules` directory. We have decided to rename this to `plugins`.

Additionally, we have decided on a new set of interface names and the plugin directories should be updated to match. These should be as follows:
- algorithms
- boundaries
- colormaps
- filename_formats
- interpolators
- output_formats
- procflows
- readers
- title_formats

I am making a new issue for this to avoid creating conflicts in a larger, ongoing feature branch.

### Checklist for Completion
* [ ] Move `interface_modules` to `plugins`
* [ ] Update plugin directory names
* [ ] Make necessary changes to the code to look in the `plugins` directory
* [ ] Make necessary code changes to use the updated plugin directories
* [ ] Run tests

**Comment by mindyls** [comment]
@jsolbrig This looks good to me - @cpcamacho any thoughts on the interface names, and/or renaming interface_modules -> plugins?

**Comment by jsolbrig** [comment]
Note that most of the renaming has already taken place in #78. This just updates the plugin directories to match the new naming scheme. Please take a look at #78 if you dislike the updated naming scheme.

**Comment by jsolbrig** [comment]
This is complete. Closing.
