### ISSUE TITLE
Add working plugin validation function to `BaseInterface` class

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#72]
# Requested Update

### Description
Each module-based plugin contains a callable and specific global variables. The global variables are the same for all interfaces. Each different interface expects a specific call signature for the plugin's callable. We should implement a method on `BaseInterface` that is able to validate both the required global variables and the call signature for the plugin's callable.

We should also implement a function that can validate all of an interface's plugins. This would simply loop through all found plugins and call the single-plugin validation function.

### Decisions
What should the methods be named? Currently, the stubs that are there are named `is_valid` and `test_interface_plugins`, but I feel that `is_valid` is not descriptive and `test_interface_plugins` doesn't quite describe what the function does. Options:

**is_valid**
- is_valid
- plugin_is_valid
- is_valid_plugin
- is_plugin_valid

**test_interface_plugins**
- all_valid
- plugins_all_valid
- all_valid_plugins
- all_plugins_valid

### Implementation
**is_valid**
`is_valid` should be defined in `BaseInterface` and should take the name of the plugin to be validated, then run validation. Validation should test three things:
1. There is a valid module-level docstring
2. The following module-level variables exist and are valid
  - name - Must be a valid Python identifier
  - interface - Must be the name of an existing interface
  - family - Must be a known family for its interface
  - description - Must be a single line, no longer than 128 characters
3. There must be a callable named `callable` that:
  - Contains a docstring
  - Matches the interface's required call signature

**all_valid**
`all_valid` just return the result of `all([interface.is_valid(plg.name) for plg in interfaces.get_plugins()])`.

**Call signature validation**
I'm not entirely sure how this should be done at this point. I think it could be done in a couple of different ways, each of which appears to be complicated. All solutions will rely on some use of `inspect.signature`.

1. We could set `MyInterface.required_positionals` and `MyInterface.required_keywords` then use those to compare against the contents of `sig = inspect.signature(myplugin.call)`. We would loop over each parameter in `sig.parameters`, ensure that it is in either `required_positionals` or `required_keywords`, then if it is in `required_keywords`, ensure that it has a default value.
2. We could construct a required signature using `inspect.Signature` and `inspect.Parameter`, then compare the result against `sig` using `required_sig == sig`. This appears to work correctly where identical signatures return `True`, even when `required_sig is sig` returns `False`.

- In option 1, I don't know if we need to test whether the default value is equal or not. I think it would be a good idea.
- In option 2, I don't know if building the signature will be too complicated.

### Checklist for Completion
* [ ] Create a checklist

**Comment by mindyls** [comment]
@jsolbrig I think "is_valid" and "all_valid" could work.  Because you are just testing the plugin to see if it "is valid".  And you are testing the interface to see if they are "all valid".  But I'm not set.  I think setting "required_positionals" and "required_keywords" could work for call signature inspection - not set either way.  @cpcamacho thoughts?

**Comment by jsolbrig** [comment]
It looks to me like this issue is complete. The functions `plugin_is_valid` and `plugins_all_valid` have been implemented on both `BaseYamlInterface` and `BaseModuleInterface`.

I'd like to have @mindy look this over to be sure that the current testing methods are sufficient.

**Comment by jsolbrig** [comment]
This is long complete. Closing.
