### ISSUE TITLE
DRAFT: Consider adding interface attribute to plugins and update setup.py to use a single GeoIPS namespace

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#76]
# Dummy Issue - Needs to be written

Essentially, this pertains to adding an `interface` attribute to module-based plugin classes and an `interface` variable to the plugin modules themselves. This may make it easier to manage plugins without needing to abstract which interface they belong to into `setup.py` or `pyproject.toml`.

# Requested Update

### Description
*  [ In 2-3 sentences briefly describe the required bug fix or feature with this issue. ]

### Background and Motivation
*  [ OPTIONAL: Provide additional detailed information and background related to this issue ]

### Alternative Solutions
*  [ OPTIONAL: If appropriate, list alternative fixes that could be considered]
  
### Environment
*  [ IF APPROPRIATE: Corresponding repository versions ]

### Code to demonstrate issue
*  [ IF APPROPRIATE: Can include steps here to identify/demonstrate bug fix or desired feature ]

### Checklist for Completion
* [ ]

**Comment by mindyls** [comment]
@jsolbrig This could work.

**Comment by jsolbrig** [comment]
This has been superseded by other work.
