### ISSUE TITLE
Add libgeos-dev to system dependencies

### ISSUE THREAD

**Issue by lance-wilson** [NRLMMD-GEOIPS/geoips#80]
# Requested Update

### Description
*  Add libgeos-dev to system dependencies in documentation.

### Background and Motivation
*  libgeos-dev is required to install cartopy using pip.  Adding the requirement will eliminate the need to have cartopy pre-installed for non-conda-based installations.

### Alternative Solutions
*  Require cartopy to be pre-installed
*  Require use of conda-based installation
  
### Environment
* geoips >= 1.6.1

### Checklist for Completion
* [x] Requirement to have libgeos-dev installed added to documentation

**Comment by mindyls** [comment]
https://github.com/NRLMMD-GEOIPS/geoips/pull/82
Complete with merge of #82
