### ISSUE TITLE
Should not attempt to push images to ghcr.io when PR is created

### ISSUE THREAD

**Issue by jsolbrig** [NRLMMD-GEOIPS/geoips#83]
# Requested Update

### Description
The action that pushes a built docker image to ghcr.io should not run when a PR is created. It should run when the merge occurs.

### Background and Motivation
Running this action from a fork causes the action to fail with 403 "Forbidden" when pushing the image to ghcr.io.
```
ERROR: failed to solve: failed to push ghcr.io/nrlmmd-geoips/geoips:latest: unexpected status: 403 Forbidden
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/nrlmmd-geoips/geoips:latest: unexpected status: 403 Forbidden
```

### Solution
While it would still be good to test building the docker image on forks, the push should probably be limited to `push` events to the `main` branch. 

### Checklist for Completion
* [ ] Update actions to only push the Docker image for `push` events on `main`
* [ ] Test CI from a fork to ensure that it doesn't attempt to push the image, but still attempts to build it

**Comment by mindyls** [comment]
Tested with merge of https://github.com/NRLMMD-GEOIPS/geoips/pull/82
